In [17]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

In [18]:
data = pd.read_excel(r"C:\Users\Sarvesh PV\Desktop\Semester 5\AML\tennis.xlsx")
data

     outlook  temp humidity  windy play
0      sunny   hot     high  False   no
1      sunny   hot     high   True   no
2   overcast   hot     high  False  yes
3      rainy  mild     high  False  yes
4      rainy  cool   normal  False  yes
5      rainy  cool   normal   True   no
6   overcast  cool   normal   True  yes
7      sunny  mild     high  False   no
8      sunny  cool   normal  False  yes
9      rainy  mild   normal  False  yes
10     sunny  mild   normal   True  yes
11  overcast  mild     high   True  yes
12  overcast   hot   normal  False  yes
13     rainy  mild     high   True   no

In [19]:
col = list(data.columns)
col

['outlook', 'temp', 'humidity', 'windy', 'play']

In [20]:
le = LabelEncoder()
for i in col:
    label = le.fit_transform(data[i])
    data = data.drop(i,axis=1)
    data[i] = label
data

    outlook  temp  humidity  windy  play
0         2     1         0      0     0
1         2     1         0      1     0
2         0     1         0      0     1
3         1     2         0      0     1
4         1     0         1      0     1
5         1     0         1      1     0
6         0     0         1      1     1
7         2     2         0      0     0
8         2     0         1      0     1
9         1     2         1      0     1
10        2     2         1      1     1
11        0     2         0      1     1
12        0     1         1      0     1
13        1     2         0      1     0

In [21]:
col.remove('play')
col

['outlook', 'temp', 'humidity', 'windy']

In [22]:
def Bagging(n_estimator,data,list_test):
    Y_pred = []
    num_sample_instances = len(data)//n_estimator
    for i in range(n_estimator):
        df = data.sample(num_sample_instances)
        X = df.drop('play',axis=1)
        Y = df['play']
        clf = LogisticRegression()
        clf_model = clf.fit(X,Y)
        pred = clf_model.predict(list_test)
        Y_pred.append(pred)
    count_Y = Y_pred.count(1)
    count_N = Y_pred.count(0)
    if count_Y>count_N :
        print("The resultant prediction is Yes. The person enjoys")
    else :
        print("The resultant prediction is No. The person does not enjoy")
    Y_pred = []

In [29]:
Vote_list = []
test = [0,1,1,0]
test_data = pd.DataFrame(columns=col)
test_data.loc[len(test_data.index)] = test
test_data

   outlook  temp  humidity  windy
0        0     1         1      0

In [40]:
Bagging(3,data,test_data)

The resultant prediction is Yes. The person enjoys